name       : autoconf213
version    : 2.13
release    : 2
source     :
    - http://ftp.gnu.org/gnu/autoconf/autoconf-2.13.tar.gz : f0611136bee505811e9ca11ca7ac188ef5323a8e2ef19cffd3edb3cf08fd791e
homepage   : http://www.gnu.org/software/autoconf/
license    : GPL-2.0-or-later
component  : programming.tools
summary    : Autoconf is an extensible package of M4 macros that produce shell scripts
    to automatically configure software source code packages. (Legacy)
description: |
    Autoconf creates a configuration script for a package from a template file that lists the operating system features that the package can use, in the form of M4 macro calls. (Legacy)
setup      : |
    sed -i 's $(datadir)/autoconf $(datadir)/autoconf213 ' Makefile.in
    %configure --program-suffix=213
build      : |
    %make
install    : |
    %make_install prefix=%installroot%/usr/ \
        datadir=$installdir/usr/share \
        infodir=$installdir/usr/share/info \
        mandir=$installdir/usr/share/man
    mv $installdir/usr/share/info/autoconf{,213}.info
    mv $installdir/usr/share/info/standards{,213}.info
